<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest" />
    <ProjectReference Include="..\..\src\Miastro.Graphics\Miastro.Graphics.csproj" />
    <ProjectReference Include="../../src/Miastro.UI.Avalonia/Miastro.UI.Avalonia.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Miastro.Domain/Miastro.Domain.csproj" />
    <ProjectReference Include="../../src/Miastro.Application/Miastro.Application.csproj" />
    <ProjectReference Include="../../src/Miastro.Infrastructure.Platform.Linux/Miastro.Infrastructure.Platform.Linux.csproj" />
    <ProjectReference Include="../../src/Miastro.Infrastructure.Persistence/Miastro.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="../../src/Miastro.Bootstrap/Miastro.Bootstrap.csproj" />
    <ProjectReference Include="..\..\src\Miastro.Infrastructure.SwissEphemeris\Miastro.Infrastructure.SwissEphemeris.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Miastro.Infrastructure.Geography/Miastro.Infrastructure.Geography.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Miastro.Infrastructure.Time/Miastro.Infrastructure.Time.csproj" />
    <ProjectReference Include="..\..\src\Miastro.Graphics.Skia\Miastro.Graphics.Skia.csproj" />
  </ItemGroup>
</Project>