<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Miastro.Application/Miastro.Application.csproj" />
    <ProjectReference Include="../Miastro.Bootstrap/Miastro.Bootstrap.csproj" />
    <ProjectReference Include="..\Miastro.Graphics\Miastro.Graphics.csproj" />
    <ProjectReference Include="..\Miastro.Graphics.Skia\Miastro.Graphics.Skia.csproj" />
  </ItemGroup>

</Project>
