// <auto-generated />
using System;
using Miastro.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Miastro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MiastroDbContext))]
    [Migration("20260820180432_Phase5PersonFunctionalSchema")]
    partial class Phase5PersonFunctionalSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Miastro.Infrastructure.Persistence.Entities.BirthDataEntity", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AmbiguousEarlierInstantUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AmbiguousEarlierOffsetSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AmbiguousLaterInstantUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AmbiguousLaterOffsetSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmbiguousSelectedCandidate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AmbiguousSelectionRecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DayPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GeoNameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HistoricalOffsetSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IanaTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("LocalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<bool>("ManualCoordinateOverride")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OriginalGeoNamesLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("OriginalGeoNamesLongitude")
                        .HasColumnType("REAL");

                    b.Property<TimeOnly?>("RangeEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("RangeStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedInstantUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subregion")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("TemporalResolutionState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimePrecision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TzdbVersion")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.HasIndex("GeoNameId");

                    b.HasIndex("IanaTimeZoneId");

                    b.ToTable("BirthData", (string)null);
                });

            modelBuilder.Entity("Miastro.Infrastructure.Persistence.Entities.CurrentResidenceEntity", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GeoNameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IanaTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.HasIndex("GeoNameId");

                    b.ToTable("CurrentResidences", (string)null);
                });

            modelBuilder.Entity("Miastro.Infrastructure.Persistence.Entities.PersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastConsultationAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivateNote")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirstName");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("LastConsultationAtUtc");

                    b.HasIndex("LastName");

                    b.HasIndex("NormalizedName");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("Miastro.Infrastructure.Persistence.Entities.PersonHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "OccurredAtUtc");

                    b.ToTable("PersonHistory", (string)null);
                });

            modelBuilder.Entity("Miastro.Infrastructure.Persistence.Entities.BirthDataEntity", b =>
                {
                    b.HasOne("Miastro.Infrastructure.Persistence.Entities.PersonEntity", "Person")
                        .WithOne("BirthData")
                        .HasForeignKey("Miastro.Infrastructure.Persistence.Entities.BirthDataEntity", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Miastro.Infrastructure.Persistence.Entities.CurrentResidenceEntity", b =>
                {
                    b.HasOne("Miastro.Infrastructure.Persistence.Entities.PersonEntity", "Person")
                        .WithOne("CurrentResidence")
                        .HasForeignKey("Miastro.Infrastructure.Persistence.Entities.CurrentResidenceEntity", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Miastro.Infrastructure.Persistence.Entities.PersonHistoryEntity", b =>
                {
                    b.HasOne("Miastro.Infrastructure.Persistence.Entities.PersonEntity", "Person")
                        .WithMany("History")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Miastro.Infrastructure.Persistence.Entities.PersonEntity", b =>
                {
                    b.Navigation("BirthData");

                    b.Navigation("CurrentResidence");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
