<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Miastro.Graphics\Miastro.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <EmbeddedResource Include="Resources/Fonts/SourceSans3-Regular.ttf"
                      LogicalName="Miastro.Graphics.Skia.Resources.Fonts.SourceSans3-Regular.ttf" />
    <EmbeddedResource Include="Resources/Fonts/SourceSans3-LICENSE.md"
                      LogicalName="Miastro.Graphics.Skia.Resources.Fonts.SourceSans3-LICENSE.md" />
  </ItemGroup>

</Project>
